#+TITLE: noctua-repl README.org
#+Options: num:nil
#+STARTUP: odd
#+Style: <style> h1,h2,h3 {font-family: arial, helvetica, sans-serif} </style>

* Overview

  This is a REPL environment for the Noctua annotation tool.

* Usage

  Given that you have logged in to a Noctua instance, look at the URL
  and copy your token (the variable is "barista_token").

  Know your target installation well enough to know where your Barista
  is hiding. Copy that URL down.

  Should then be as simple as:

  : npm install
  : node ./bin/noctua-repl.js --token=xyz321abc987 --barista http://127.0.0.1:3400

* Examples

  Get all of the meta-information for the current instance.

  : get_meta()

  Assign environment to a known model, then add a couple of new
  individuals to it.

  : model_id = 'gomodel:taxon_9606-5539842e0000002'
  : add_individual('GO:0022008')
  : add_individual(intersection(['GO:0022008', 'GO:0008150']))

  Add a new model, which gets the default assignment when done. Then
  add two new individuals as arguments to a new fact.

  : add_model()
  : var r = new_request_set()
  : r.add_fact([r.add_individual('GO:0022008'), r.add_individual('GO:0008150'), 'part_of'] )
  : request_with(r)

* Limitations/TODOs

  While the full API is available, there could be some better memory
  of actions so one is not always looking up the last individual IDs.

  Also, it is still asynchronous, so you need to wait until it has
  completed if you want to run the next in a series of commands.
